<?xml version="1.0"?>
<package format="3">
  <name>wheeltec_ultrasonic</name>
  <version>0.1.0</version>
  <description>Utilities to convert Wheeltec Supersonic distances to Range and PointCloud2 for Nav2.</description>
  <maintainer email="maintainer@example.com">wheeltec</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>robot_interfaces</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

